# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# locale: en-GB
title: pencer.io
subtitle: "Eat. Sleep. Hack. Repeat"
description: "Hacking. A lot of hacking. Mostly CTFs, but then other stuff too when I get round to it."
repository: "pencer-io/pencer-io.github.io"

twitter_username: pencer_io
github_username: pencer-io
minimal_mistakes_skin: dark
# teaser: /assets/images/500x300.png
logo: "/assets/images/masthead.png"
search: true
breadcrumbs: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-18588186-2"
    anonymize_ip: false # default

comments:
  provider: "disqus"
  disqus:
    shortname: "pencer-io"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : 
  avatar : "/assets/images/BlackUnicorn.png"
  bio    : "Cyber Security, Penetration Testing, Hacking, Coding and Web enthusiast."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://pencer.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pencer_io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pencer-io/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pencer_io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pencer-io/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      #sidebar:
      #- title: "Title"
      #  image: http://placehold.it/350x250
      #  image_alt: "image"
      #  text: "Some text here."
      #- title: "Another Title"
      #  text: "More text here."

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
